### ISSUE TITLE
Create a github.io for ecc

### ISSUE THREAD

**Issue by igormcoelho** [andreacorbellini/ecc#4]
Congratulations for this amazing tool! I think it deserves a github.io domain (instead of cdn raw git)... so it would easily become: andreacorbellini.github.io/ecc

**Comment by andreacorbellini** [comment]
Hi,

As far as I know, in order to be hosted under andreacorbellini.github.io/ecc, it would need to be part of the same repository as my blog, but this is something I would like to avoid (I want people to be able to fork/star/watch this repository without any conflicts with other material). I also cannot create a separate github.io domain (say, ecc.github.com) as I'm limited to only one domain. So I don't believe that what you're asking for would be possible, but please correct me if I'm wrong.

Cheers,
Andrea

**Comment by enriquesl-git** [comment]
I have my fork of your tool running under github.io without needing a
separate domain:

https://enriquesl-git.github.io/ecc/interactive/reals-add.html

This is the only option that I touched on settings:

[image: image.png]


--
Enrique Santos

**Comment by igormcoelho** [comment]
Hi Andrea, you can keep this repo as it is now, it will become a directory exactly as the link I wrote. You only need to create another repo called youruser.github.io
You can even redirect your actual website to this new repo (github cobfigures letsencrypt for you too). We do this for our group neoresearch.io, which is hosted on github.com/neoresearch if you need an example :)
We have plenty of tools running in different folders like that, example, neoresearch.io/smacco

**Comment by andreacorbellini** [comment]
Okay, thanks to both of you for letting me know! I will take a look as soon
as I get a chance!

>

**Comment by andreacorbellini** [comment]
I started serving the ECC stuff under andrea.corbellini.name/ecc (e.g. https://andrea.corbellini.name/ecc/interactive/reals-add.html?px=-1&py=4&qx=1&qy=2) and updated all the links in the blog posts. Thank you very much for letting me know that it was possible!

Also, while doing that, I realized that RawGit is going away. So double thanks for that!

**Comment by igormcoelho** [comment]
it's working nice !! thanks!
